/* eslint-disable no-restricted-globals */
// PlateRunner Lab service worker — Workbox via CRA's built-in support.
// CRA's react-scripts injects self.__WB_MANIFEST at build time.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

self.skipWaiting();
clientsClaim();

// On activate, clear stale caches from previous SW versions
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((n) => n === 'static-assets') // old CacheFirst image cache
          .map((n) => caches.delete(n))
      )
    )
  );
});

// Precache all static assets (JS, CSS, HTML) generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Single-page app: serve index.html for all navigation requests under /lab
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url, sameOrigin }) => {
    if (!sameOrigin) return false;
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache API lab endpoints with NetworkFirst (fresh data preferred, cache as fallback)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/lab/'),
  new NetworkFirst({
    cacheName: 'lab-api-cache',
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 24 * 60 * 60 }),
    ],
  })
);

// Cache static assets (images, fonts) with StaleWhileRevalidate
// so updated images are fetched in the background and available on next load
registerRoute(
  ({ request }) =>
    request.destination === 'image' || request.destination === 'font',
  new StaleWhileRevalidate({
    cacheName: 'static-assets-v2',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  })
);

// Cache JS/CSS with StaleWhileRevalidate
registerRoute(
  ({ request }) =>
    request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({ cacheName: 'static-resources' })
);

// Allow the web app to trigger skipWaiting via a message
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
